export const personalInfo = {
  name: "Yoon Jae Chang",
  title: "Software Developer",
  bio: "Hey, I'm Yoon Jae Chang. Here, you can check out what I'm working on. I try my best to create things with ❤",
  email: "yoonjaechang244@gmail.com",
  github: "https://github.com/yoonjae-chang",
  linkedin: "https://linkedin.com/in/yoonjaechang",
};

export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "Full-stack e-commerce solution with React, Node.js, and PostgreSQL",
    image: "/project-placeholder.jpg",
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
    demoUrl: "https://demo-ecommerce.example.com",
    githubUrl: "https://github.com/yoonjae-chang/ecommerce-platform",
    featured: true,
  },
  {
    id: 2,
    title: "Task Management App",
    description: "Collaborative task management tool with real-time updates",
    image: "/project-placeholder.jpg",
    technologies: ["Next.js", "TypeScript", "Prisma", "Socket.io"],
    demoUrl: "https://task-manager.example.com",
    githubUrl: "https://github.com/yoonjae-chang/task-manager",
    featured: true,
  },
  {
    id: 3,
    title: "Weather Dashboard",
    description: "Beautiful weather app with location-based forecasts",
    image: "/project-placeholder.jpg",
    technologies: ["React", "OpenWeather API", "Chart.js"],
    demoUrl: "https://weather-dashboard.example.com",
    githubUrl: "https://github.com/yoonjae-chang/weather-dashboard",
    featured: false,
  },
  {
    id: 4,
    title: "Portfolio Website",
    description: "Personal portfolio built with Next.js and Tailwind CSS",
    image: "/project-placeholder.jpg",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS"],
    demoUrl: "https://yoonjae-chang.dev",
    githubUrl: "https://github.com/yoonjae-chang/portfolio",
    featured: false,
  },
  {
    id: 5,
    title: "Chat Application",
    description: "Real-time chat app with rooms and file sharing",
    image: "/project-placeholder.jpg",
    technologies: ["React", "Firebase", "Material-UI"],
    demoUrl: "https://chat-app.example.com",
    githubUrl: "https://github.com/yoonjae-chang/chat-app",
    featured: false,
  },
  {
    id: 6,
    title: "Data Visualization Tool",
    description: "Interactive data visualization dashboard for analytics",
    image: "/project-placeholder.jpg",
    technologies: ["D3.js", "React", "Python", "FastAPI"],
    demoUrl: "https://data-viz.example.com",
    githubUrl: "https://github.com/yoonjae-chang/data-visualization",
    featured: false,
  },
];

export const experiences = [
  {
    id: 1,
    company: "Tech Innovations Inc.",
    position: "Senior Software Developer",
    duration: "2022 - Present",
    description: "Lead development of scalable web applications using React and Node.js. Mentored junior developers and implemented CI/CD pipelines.",
    achievements: [
      "Increased application performance by 40%",
      "Led a team of 5 developers",
      "Implemented automated testing reducing bugs by 60%",
    ],
  },
  {
    id: 2,
    company: "StartupXYZ",
    position: "Full Stack Developer",
    duration: "2020 - 2022",
    description: "Developed and maintained multiple client projects using modern web technologies. Collaborated with design teams to create user-friendly interfaces.",
    achievements: [
      "Built 10+ client websites from scratch",
      "Improved code review process",
      "Reduced deployment time by 50%",
    ],
  },
  {
    id: 3,
    company: "Digital Solutions Co.",
    position: "Junior Developer",
    duration: "2019 - 2020",
    description: "Started career developing responsive websites and learning modern development practices. Gained experience in agile development methodologies.",
    achievements: [
      "Completed 20+ projects successfully",
      "Learned React, Node.js, and cloud deployment",
      "Contributed to open source projects",
    ],
  },
];

export const skills = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "PostgreSQL",
  "MongoDB",
  "AWS",
  "Docker",
  "Git",
  "Tailwind CSS",
];
